### ISSUE TITLE
Android Manifest not working for Android 12

### ISSUE THREAD

**Issue by maxi-w** [friyiajr/BluetoothLowEnergySample#1]
After installing the sample app on a device with Android 12 the ble managers device scan returned an error:

`{"message":"Cannot start scanning operation","errorCode":600,"attErrorCode":null,"iosErrorCode":null,"androidErrorCode":null,"reason":"Bluetooth cannot start (code 0)","name":"BleError"}`

The fix as described in https://github.com/dotintent/react-native-ble-plx/issues/966 was to change the Android Manifest to:
```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.BLUETOOTH"/>
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
<uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE"/>
<uses-permission android:name="android.permission.BLUETOOTH_SCAN"/>
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT"/>
<uses-feature android:name="android.hardware.bluetooth" android:required="true"/>
<uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>
```

**Comment by friyiajr** [comment]
Thank you for bringing this up @maxi-w! I am going to do my best to test this and try to get it into the sample code!

**Comment by friyiajr** [comment]
I am also planning on making a video to address these changes once I have everything worked out
